# Generated by Django 2.0.7 on 2018-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this book', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a book genre (e.g. Science Fiction, None Fiction, Cybersecurity, Military history, Romance etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter a the book's natural language (e.g. English, French, Japanese etc.)", max_length=200),
        ),
    ]
