# Generated by Django 2.1 on 2018-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180819_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inner_book_color',
            field=models.CharField(blank=True, choices=[('w', 'White'), ('m', 'Milk'), ('b', 'Black')], default='w', help_text='The inner color of the book which may either by white or milk color', max_length=1, verbose_name='INNER COLOUR'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.CharField(blank=True, help_text='The number of pages of book', max_length=10, verbose_name='PAGE NUMBER'),
        ),
    ]
