# Generated by Django 2.1 on 2018-08-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180819_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book with the maximum length of 1000 characters', max_length=2000),
        ),
    ]
