# Generated by Django 2.1 on 2018-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180820_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='inner_book_color',
            new_name='colorstatus',
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book with the maximum length of 2000 characters', max_length=2000),
        ),
    ]
