# Generated by Django 2.1 on 2018-08-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180820_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='colorstatus',
            new_name='status',
        ),
    ]
