# Generated by Django 2.1.1 on 2018-09-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180820_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(help_text='The number of pages of book', verbose_name='PAGE NUMBER'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('w', 'White'), ('m', 'Milk'), ('b', 'Black')], default='w', help_text='The inner color of the book which may either by white or milk color', max_length=1, verbose_name='INNER COLOUR'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book with the maximum length of 3000 characters', max_length=3000),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability status', max_length=1),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction, None Fiction, Cybersecurity, Military history, Romance etc.', max_length=30),
        ),
    ]
