# Generated by Django 2.1.1 on 2018-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180908_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date format : YYYY-MM-DD', null=True),
        ),
    ]
